### PR TITLE
Move to standard and fix spinner is not shown while loading

### PR DESCRIPTION
**Pull request by miduga**
* Fix spinner, to be shown while image is loading.
* Move pre-commit-rules to latest version with standard linter.

### CODE REVIEW

**Comment by FranDelaCasa** [comment]
👍

**Comment by ruben-martin-lozano** [comment]
👍

**Comment by davecarter** [comment]
👍 

... mising semicolons :(

**Comment by kikoruiz** [comment]
👍

**Comment by kikoruiz** [comment]
Se me hace raro la verdad... 😭

**Comment by miduga** [comment]
image

Para vosotros @kikoruiz @davecarter

**Pull request merged**
